const data  =   {
    products:   [
       {
            _id: '1',
            name:   'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120, 
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
      },
            {
                _id: '2',
                name:   'Adidas Fit Shirt',
                category: 'Shirts',
                image: '/images/p2.jpg',
                price: 100,
                countInStock: 20,
                brand: 'Adidas',
                rating: 4.0,
                numReviews: 10,
                description: 'high quality product',
  },
                {
                    _id: '3',
                    name:   'Lacoste Free Shirt',
                    category: 'Shirts',
                    image: '/images/p3.jpg',
                    price: 220,             countInStock: 0,
                    brand: 'Lacoste',
                    rating: 4.8,
                    numReviews: 17,
                    description: 'high quality product',
},
                    {
                        _id: '4',
                        name:   'Puma slim Pants',
                        category: 'Pants',
                        image: '/images/p4.jpg',  countInStock: 15,
                        price: 65, 
                        brand: 'Puma',
                        rating: 4.5,
                        numReviews: 10,
                        description: 'high quality product',
                    },
                        {
                            _id: '5',
                            name:   'Adidas Fit pant',
                            category: 'pants',
                            image: '/images/p5.jpg',
                            price: 139, countInStock: 5,
                            brand: 'Adida',
                            rating: 4.5,
                            numReviews: 50,
                            description: 'high quality product',
                        },
                        {
                            _id: '6',
                            name:   'Adidas Fit pant',
                            category: 'pants',
                            image: '/images/p6.jpg',
                            price: 139, countInStock: 12,
                            brand: 'Adida',
                            rating: 4.5,
                            numReviews: 50,
                            description: 'high quality product',
                        },
                      
    ],
} 
export default data;